<a href="https://colab.research.google.com/github/HalyshAnton/ITStep-AI/blob/superwised_learning/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

Мабуть, найважливішою структурою даних oabdas є `DataFrame`. Це таблична структура, тісно інтегрована з `Series`.

In [90]:
import numpy as np
import pandas as pd

Ми проведемо аналіз країн G7 і зараз розглянемо DataFrames.


<img width="700" src="https://user-images.githubusercontent.com/872296/38153492-72c032ca-3443-11e8-80f4-9de9060a5127.png" />

Створення `DataFrame` вручну може бути виснажливим. У 99% випадків ви отримуватимете дані з бази даних, файлу CSV або Інтернету. Але все ж ви можете створити DataFrame, вказавши стовпці та значення:

In [128]:
df = pd.DataFrame({
    'Name': [
        'Canada',
        'France',
        'Germany',
        'Italy',
        'Japan',
        'United Kingdom',
        'United States',
    ],
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
})

In [92]:
df

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [93]:
df.head()  # перші 5 рядків

      Name  Population      GDP  Surface Area    HDI Continent
0   Canada      35.467  1785387       9984670  0.913   America
1   France      63.951  2833687        640679  0.888    Europe
2  Germany      80.940  3874437        357114  0.916    Europe
3    Italy      60.665  2167744        301336  0.873    Europe
4    Japan     127.061  4602367        377930  0.891      Asia

`DataFrame` також мають індекси рядків. Як ви можете бачити в «таблиці» вище, pandas автоматично призначила числовий зромтаючий індекс кожному «рядку» в нашому DataFrame.

Стовпці "індексуються" назвами типу `str`

In [95]:
df.columns

Index(['Name', 'Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [96]:
# df.columns = df.columns.str.lower()

In [97]:
df

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [98]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          7 non-null      object
 1   Population    7 non-null      float64
 2   GDP           7 non-null      int64
 3   Surface Area  7 non-null      int64
 4   HDI           7 non-null      float64
 5   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(2)
memory usage: 468.0+ bytes

In [20]:
df.size

42

In [21]:
df.shape

(7, 6)

In [22]:
df.dtypes

Name             object
Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

## Індексування та відбір
Окремі стовпці в DataFrame можна вибирати за допомогою звичайного індексування. Кожен стовпець представлено як `Series`:

In [102]:
df

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [104]:
df['HDI']

0    0.913
1    0.888
2    0.916
3    0.873
4    0.891
5    0.907
6    0.915
Name: HDI, dtype: float64

In [108]:
col_names = ['Population', "Name", 'Population']
df[col_names]

df[['Population', "Name"]]

   Population            Name
0      35.467          Canada
1      63.951          France
2      80.940         Germany
3      60.665           Italy
4     127.061           Japan
5      64.511  United Kingdom
6     318.523   United States

In [109]:
df.Name

0            Canada
1            France
2           Germany
3             Italy
4             Japan
5    United Kingdom
6     United States
Name: Name, dtype: object

In [111]:
# рядок з індексом 3:5
df.iloc[3:5, :]

    Name  Population      GDP  Surface Area    HDI Continent
3  Italy      60.665  2167744        301336  0.873    Europe
4  Japan     127.061  4602367        377930  0.891      Asia

In [112]:
# стовпчики з індексами 0, 1, -1
col_inds = [0, 1, -1]
df.iloc[:, col_inds]

df.iloc[:, [0, 1, -1]]

df.iloc[2:3, [4, 2]]

     HDI      GDP
2  0.916  3874437

Кілька стовпців також можна вибрати подібно до `numpy` і `Series`:

In [27]:
df[['Name', 'Population']]

             Name  Population
0          Canada      35.467
1          France      63.951
2         Germany      80.940
3           Italy      60.665
4           Japan     127.061
5  United Kingdom      64.511
6   United States     318.523

Для індексування `DataFrame` як матрицю `numpy` можна використовувати метод iloc

In [28]:
df.iloc[:, 1:2]

   Population
0      35.467
1      63.951
2      80.940
3      60.665
4     127.061
5      64.511
6     318.523

Якщо потрібно вказувати не індекси, а назви стовпців, то використовуємо метод loc

In [29]:
df.loc[:, ['Name', 'Population']]

             Name  Population
0          Canada      35.467
1          France      63.951
2         Germany      80.940
3           Italy      60.665
4           Japan     127.061
5  United Kingdom      64.511
6   United States     318.523

## Умовний вибір (булеві масиви)

Ми бачили умовний вибір, застосований в `numpy`, і він працюватиме таким же чином для `DataFrame`.

In [114]:
df['Continent'] == 'Europe'

0    False
1     True
2     True
3     True
4    False
5     True
6    False
Name: Continent, dtype: bool

In [116]:
mask = df['Continent'] == 'Europe'
mask

0    False
1     True
2     True
3     True
4    False
5     True
6    False
Name: Continent, dtype: bool

In [117]:
df[mask]

             Name  Population      GDP  Surface Area    HDI Continent
1          France      63.951  2833687        640679  0.888    Europe
2         Germany      80.940  3874437        357114  0.916    Europe
3           Italy      60.665  2167744        301336  0.873    Europe
5  United Kingdom      64.511  2950039        242495  0.907    Europe

In [118]:
df[df['Continent'] == "Europe"]

             Name  Population      GDP  Surface Area    HDI Continent
1          France      63.951  2833687        640679  0.888    Europe
2         Germany      80.940  3874437        357114  0.916    Europe
3           Italy      60.665  2167744        301336  0.873    Europe
5  United Kingdom      64.511  2950039        242495  0.907    Europe

In [119]:
# декілька умов
# європейське з HDI >= 0.9
df[(df['Continent'] == 'Europe') & (df['HDI'] >= 0.9)]

             Name  Population      GDP  Surface Area    HDI Continent
2         Germany      80.940  3874437        357114  0.916    Europe
5  United Kingdom      64.511  2950039        242495  0.907    Europe

In [120]:
df[(df['Continent'] == 'Europe') | (df['HDI'] >= 0.9)]

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [121]:
df[~(df['Continent'] == 'Europe')]

            Name  Population       GDP  Surface Area    HDI Continent
0         Canada      35.467   1785387       9984670  0.913   America
4          Japan     127.061   4602367        377930  0.891      Asia
6  United States     318.523  17348075       9525067  0.915   America

In [122]:
mask = df['Continent'] == 'Europe'  # чи в Європі
mask = ~mask    # не в Європі
df[mask]

            Name  Population       GDP  Surface Area    HDI Continent
0         Canada      35.467   1785387       9984670  0.913   America
4          Japan     127.061   4602367        377930  0.891      Asia
6  United States     318.523  17348075       9525067  0.915   America

In [37]:
# & -- and
# | -- or
# ~ -- not

In [38]:
df

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [39]:
df['Population'] > 70

0    False
1    False
2     True
3    False
4     True
5    False
6     True
Name: Population, dtype: bool

In [40]:
df[df['Population'] > 70]

            Name  Population       GDP  Surface Area    HDI Continent
2        Germany      80.940   3874437        357114  0.916    Europe
4          Japan     127.061   4602367        377930  0.891      Asia
6  United States     318.523  17348075       9525067  0.915   America

Булева маска дозволяє вибрати потрібні рядки, враховуючи всі стовпчики. Якщо потрібно вибрати лише деякі стовпці, то використовуємо метод `.loc`

In [41]:
df.loc[df['Population'] > 70, ['Name']]

            Name
2        Germany
4          Japan
6  United States

In [42]:
df.loc[df['Population'] > 70, ['Name', 'Population', 'GDP']]

            Name  Population       GDP
2        Germany      80.940   3874437
4          Japan     127.061   4602367
6  United States     318.523  17348075

## Видалення

На противагу поняттю відбору є «видалення». Замість того, щоб вказувати, які стовпці ви хочете _вибрати_, ви можете вказати, які з них ви хочете `викинути`:

In [126]:
new_df = df.drop(columns=['Population'], inplace=False)
new_df

In [127]:
df

             Name       GDP  Surface Area    HDI Continent
0          Canada   1785387       9984670  0.913   America
1          France   2833687        640679  0.888    Europe
2         Germany   3874437        357114  0.916    Europe
3           Italy   2167744        301336  0.873    Europe
4           Japan   4602367        377930  0.891      Asia
5  United Kingdom   2950039        242495  0.907    Europe
6   United States  17348075       9525067  0.915   America

In [129]:
df.drop(columns=['Population', 'HDI'])

             Name       GDP  Surface Area Continent
0          Canada   1785387       9984670   America
1          France   2833687        640679    Europe
2         Germany   3874437        357114    Europe
3           Italy   2167744        301336    Europe
4           Japan   4602367        377930      Asia
5  United Kingdom   2950039        242495    Europe
6   United States  17348075       9525067   America

In [49]:
df.drop(['Population', 'HDI'], axis=1)

             Name       GDP  Surface Area Continent
0          Canada   1785387       9984670   America
1          France   2833687        640679    Europe
2         Germany   3874437        357114    Europe
3           Italy   2167744        301336    Europe
4           Japan   4602367        377930      Asia
5  United Kingdom   2950039        242495    Europe
6   United States  17348075       9525067   America

In [50]:
df.drop(['Population', 'HDI'], axis='columns')

             Name       GDP  Surface Area Continent
0          Canada   1785387       9984670   America
1          France   2833687        640679    Europe
2         Germany   3874437        357114    Europe
3           Italy   2167744        301336    Europe
4           Japan   4602367        377930      Asia
5  United Kingdom   2950039        242495    Europe
6   United States  17348075       9525067   America

Усі ці методи `drop` повертають новий `DataFrame`. Якщо ви хочете змінити його "на місці", ви можете скористатися атрибутом `inplace`

In [130]:
df

             Name  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America


## Операції

In [131]:
df[['Population', 'GDP']]

   Population       GDP
0      35.467   1785387
1      63.951   2833687
2      80.940   3874437
3      60.665   2167744
4     127.061   4602367
5      64.511   2950039
6     318.523  17348075

In [132]:
#df['Population'] = df.icol[0, 0]

df['GDP per Capita'] = df['GDP'] / df['Population']

In [134]:
df['Continent'] = df['Continent'].str.upper()

In [135]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330

In [56]:
df['Population'] * 6

0     212.802
1     383.706
2     485.640
3     363.990
4     762.366
5     387.066
6    1911.138
Name: Population, dtype: float64

In [136]:
df['Population'].min()

35.467

Аналогічно до `numpy` можна виконувати операції між рядками. Операції виконуються поелементно.

In [137]:
df['GDP'] / df['Population']

0    50339.385908
1    44310.284437
2    47868.013343
3    35733.025633
4    36221.712406
5    45729.239975
6    54464.120330
dtype: float64

## Зміна даних

Це просто та інтуїтивно зрозуміло. Ви можете без проблем додавати стовпці або замінювати значення для стовпців:

### Додавання нового стовпця

In [144]:
df['Language'] = ['English', 'French', 'German', 'Italian', 'Jananese', 'English', 'English']

In [145]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908,English
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437,French
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343,German
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633,Italian
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406,Jananese
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330,English

---
### Заміна значень у стовпці

In [146]:
df['Language'] = 'English'

In [147]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908,English
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437,English
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343,English
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406,English
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330,English

---
### Перейменування стовпців

In [148]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    })

,Name,Population,GDP,Surface Area,Human Development Index,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908,English
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437,English
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343,English
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406,English
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330,English

In [149]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908,English
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437,English
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343,English
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406,English
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330,English

---
### Видалення стовпців

In [64]:
df.drop(columns='Language', inplace=True)

In [65]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330

In [150]:
df.groupby(by='Continent').count()

           Name  Population  GDP  Surface Area  HDI  GDP per Capita  Language
Continent
AMERICA       2           2    2             2    2               2         2
ASIA          1           1    1             1    1               1         1
EUROPE        4           4    4             4    4               4         4

In [152]:
# загальне ввп на континент
df.groupby(by='Continent')['Population'].mean()

Continent
AMERICA    176.99500
ASIA       127.06100
EUROPE      67.51675
Name: Population, dtype: float64

---
### Зміна індексу

In [68]:
df.set_index('Name')

,Population,GDP,Surface Area,HDI,Continent,GDP per Capita
Name,,,,,,
Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908
France,63.951,2833687,640679,0.888,EUROPE,44310.284437
Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343
Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633
Japan,127.061,4602367,377930,0.891,ASIA,36221.712406
United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975
United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330

## Створення стовпців з інших стовпців

Зміна DataFrame часто передбачає поєднання різних стовпців в інші. Наприклад, у нашому аналізі країн ми могли б спробувати обчислити «ВВП на душу населення», що означає просто `GDP / Population`.

In [69]:
df[['GDP', 'Population']]

        GDP  Population
0   1785387      35.467
1   2833687      63.951
2   3874437      80.940
3   2167744      60.665
4   4602367     127.061
5   2950039      64.511
6  17348075     318.523

In [70]:
df['GDP'] / df['Population']

0    50339.385908
1    44310.284437
2    47868.013343
3    35733.025633
4    36221.712406
5    45729.239975
6    54464.120330
dtype: float64

Результатом цієї операції є ще одна `Series`, яку ви можете додати до оригінального `DataFrame`:

In [71]:
df['GDP Per Capita'] = df['GDP'] / df['Population']

In [72]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
0,Canada,35.467,1785387,9984670,0.913,AMERICA,50339.385908,50339.385908
1,France,63.951,2833687,640679,0.888,EUROPE,44310.284437,44310.284437
2,Germany,80.940,3874437,357114,0.916,EUROPE,47868.013343,47868.013343
3,Italy,60.665,2167744,301336,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930,0.891,ASIA,36221.712406,36221.712406
5,United Kingdom,64.511,2950039,242495,0.907,EUROPE,45729.239975,45729.239975
6,United States,318.523,17348075,9525067,0.915,AMERICA,54464.120330,54464.120330

## Пропущені значення

In [153]:
for i, j in zip([0, 2, 2, 5], [5, 3, 6, 3]):
  df.iloc[i, j] = np.nan

df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,9984670.0,0.913,NaN,50339.385908,English
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,English
2,Germany,80.940,3874437,NaN,0.916,EUROPE,NaN,English
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,English
5,United Kingdom,64.511,2950039,NaN,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,English

In [154]:
df.dropna(inplace=False)

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,Language
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,English
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,English
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,English

In [75]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
0,Canada,35.467,1785387,9984670.0,0.913,NaN,50339.385908,50339.385908
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,44310.284437
2,Germany,80.940,3874437,NaN,0.916,EUROPE,NaN,47868.013343
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,36221.712406
5,United Kingdom,64.511,2950039,NaN,0.907,EUROPE,45729.239975,45729.239975
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,54464.120330

Метод `.info` дозволяє дізнатись кількість непропущених значень(non-null count) у кожному стовпчику.

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            7 non-null      object
 1   Population      7 non-null      float64
 2   GDP             7 non-null      int64
 3   Surface Area    5 non-null      float64
 4   HDI             7 non-null      float64
 5   Continent       6 non-null      object
 6   GDP per Capita  6 non-null      float64
 7   Language        7 non-null      object
dtypes: float64(4), int64(1), object(3)
memory usage: 580.0+ bytes

In [159]:
df.isnull().sum()

Name              0
Population        0
GDP               0
Surface Area      2
HDI               0
Continent         1
GDP per Capita    1
Language          0
dtype: int64

In [78]:
df['Continent']

0        NaN
1     EUROPE
2     EUROPE
3     EUROPE
4       ASIA
5     EUROPE
6    AMERICA
Name: Continent, dtype: object

In [79]:
df.isnull().sum()

Name              0
Population        0
GDP               0
Surface Area      2
HDI               0
Continent         1
GDP per Capita    1
GDP Per Capita    0
dtype: int64

In [160]:
df.drop(columns=['Surface Area'])

,Name,Population,GDP,HDI,Continent,GDP per Capita,Language
0,Canada,35.467,1785387,0.913,NaN,50339.385908,English
1,France,63.951,2833687,0.888,EUROPE,44310.284437,English
2,Germany,80.940,3874437,0.916,EUROPE,NaN,English
3,Italy,60.665,2167744,0.873,EUROPE,35733.025633,English
4,Japan,127.061,4602367,0.891,ASIA,36221.712406,English
5,United Kingdom,64.511,2950039,0.907,EUROPE,45729.239975,English
6,United States,318.523,17348075,0.915,AMERICA,54464.120330,English

In [161]:
df.isnull().sum()

Name              0
Population        0
GDP               0
Surface Area      2
HDI               0
Continent         1
GDP per Capita    1
Language          0
dtype: int64

Для видалення всіх рядків, які мають хоча б одне пропущене значення можна використати метод `dropna`. Після цього бажано перевірити кількість рядків, що залишились.

In [82]:
df.dropna()

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,44310.284437
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,36221.712406
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,54464.120330

In [83]:
df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
0,Canada,35.467,1785387,9984670.0,0.913,NaN,50339.385908,50339.385908
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,44310.284437
2,Germany,80.940,3874437,NaN,0.916,EUROPE,NaN,47868.013343
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,36221.712406
5,United Kingdom,64.511,2950039,NaN,0.907,EUROPE,45729.239975,45729.239975
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,54464.120330

Для видалення рядків, які мають пропуск в конкретному стовпці, можна використати логічну маску.

In [84]:
df[~df['Continent'].isnull()]

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,44310.284437
2,Germany,80.940,3874437,NaN,0.916,EUROPE,NaN,47868.013343
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,36221.712406
5,United Kingdom,64.511,2950039,NaN,0.907,EUROPE,45729.239975,45729.239975
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,54464.120330

## Збереження

Щоб зберегти `DataFrame` як файл `csv` використовуйте метод `to_csv`

In [162]:
df.to_csv("g7_data.csv")

In [86]:
new_df = pd.read_csv('/content/g7_data.csv', index_col='Unnamed: 0')

new_df

,Name,Population,GDP,Surface Area,HDI,Continent,GDP per Capita,GDP Per Capita
0,Canada,35.467,1785387,9984670.0,0.913,NaN,50339.385908,50339.385908
1,France,63.951,2833687,640679.0,0.888,EUROPE,44310.284437,44310.284437
2,Germany,80.940,3874437,NaN,0.916,EUROPE,NaN,47868.013343
3,Italy,60.665,2167744,301336.0,0.873,EUROPE,35733.025633,35733.025633
4,Japan,127.061,4602367,377930.0,0.891,ASIA,36221.712406,36221.712406
5,United Kingdom,64.511,2950039,NaN,0.907,EUROPE,45729.239975,45729.239975
6,United States,318.523,17348075,9525067.0,0.915,AMERICA,54464.120330,54464.120330